version: "3.8"
services:
      frontend:
        build: /root/threetier_Studentapp/frontend
        container_name : frontend
        ports : 
          - 80:80
        network_mode: bridge
      backend:
        build: /root/threetier_Studentapp/backend
        container_name : backend
        ports : 
          - 8080:8080
        depends_on :
          - frontend
        network_mode: bridge
